from .userCreateView import UserCreateView
from .userDetailView import UserDetailView
from .productDetailView import ProductDetailView
from .productCreateView import ProductCreateView
from .productUpdateView import ProductUpdateView
from .productDeleteView import ProductDeleteView
from .marcaCreateView import MarcaCreateView
from .marcasListView import MarcasListView
from .categoriaCreateView import CategoriaCreateView
from .categoriasListView import CategoriasListView
from .allProductsListVIew import AllProductsListView
from .productsUserView import ProductsUserView
from .telefonoUpdateView import TelefonoUpdateView
from .contactDetailsView import ContactDetailsView
