# Generated by Django 3.2.7 on 2021-10-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technodevicesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='telefono_contacto',
            field=models.CharField(blank='', default='', max_length=16, verbose_name='Telefono_contacto'),
        ),
    ]
