# Generated by Django 3.2.7 on 2021-10-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technodevicesApp', '0002_producto_telefono_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='email_contacto',
            field=models.EmailField(blank='', default='', max_length=100, verbose_name='Email_contacto'),
        ),
    ]
