# Generated by Django 3.2.7 on 2021-10-26 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technodevicesApp', '0003_alter_producto_fecha_publicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_publicacion',
            field=models.CharField(max_length=50, verbose_name='Fecha publicación'),
        ),
    ]
