# Generated by Django 3.2.7 on 2021-10-22 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technodevicesApp', '0003_producto_email_contacto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='telefono',
        ),
        migrations.AddField(
            model_name='account',
            name='email',
            field=models.EmailField(blank='', default='', max_length=100, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='account',
            name='telefono',
            field=models.CharField(blank='', default='', max_length=15, verbose_name='Telefono'),
        ),
    ]
