# Generated by Django 3.2.7 on 2021-10-23 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technodevicesApp', '0004_auto_20211021_2330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='email_contacto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='telefono_contacto',
        ),
    ]
