from .accountSerializer import AccountSerializer
from .userSerializer import UserSerializer
from .productSerializer import ProductSerializer
from .productImagesSerializer import ProductImageSerializer
from .categoriaSerializer import CategoriaSerializer
from .marcaSerializer import MarcaSerializer
from .telefonoSerializer import TelefonoSerializer